name: Install React App Dependencies

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show current directory and react-app contents
        run: |
           pwd
             ls -l
             ls -l react-app
      - name: 📦 Install dependencies
        run: npm ci
        working-directory: react-app